<?php
/**
 * ISO Codes
 * 
 * @author Juan Pedro Gonzalez Gutierrez
 * @copyright Copyright (c) 2015 Juan Pedro Gonzalez Gutierrez
 * @license   http://www.gnu.org/licenses/gpl-3.0.en.html GPL v3
 */

namespace IsoCodes\Language\Adapter;

/**
 * https://github.com/matriphe/php-iso-639/blob/master/src/ISO639.php
 */
class StaticAdapter
{
    protected $languages = array(
        'ab' => array(
            'code'        => 'ab',
            'code2_t'     => 'abk',
            'code2_b'     => 'abk',
            'code3'       => 'abk',
            'name'        => 'Abkhaz',
            'native_name' => 'аҧсуа бызшәа, аҧсшәа',
        ),
        'aa' => array(
            'code'        => 'aa',
            'code2_t'     => 'aar',
            'code2_b'     => 'aar',
            'code3'       => 'aar',
            'name'        => 'Afar',
            'native_name' => 'Afaraf',
        ),
        'af' => array(
            'code'        => 'af',
            'code2_t'     => 'afr',
            'code2_b'     => 'afr',
            'code3'       => 'afr',
            'name'        => 'Afrikaans',
            'native_name' => 'Afrikaans',
        ),
        'ak' => array(
            'code'        => 'ak',
            'code2_t'     => 'aka',
            'code2_b'     => 'aka',
            'code3'       => 'aka',
            'name'        => 'Akan',
            'native_name' => 'Akan',
        ),
        'sq' => array(
            'code'        => 'sq',
            'code2_t'     => 'sqi',
            'code2_b'     => 'alb',
            'code3'       => 'sqi',
            'name'        => 'Albanian',
            'native_name' => 'Shqip',
        ),
        'am' => array(
            'code'        => 'am',
            'code2_t'     => 'amh',
            'code2_b'     => 'amh',
            'code3'       => 'amh',
            'name'        => 'Amharic',
            'native_name' => 'አማርኛ',
        ),
        'ar' => array(
            'code'        => 'ar',
            'code2_t'     => 'ara',
            'code2_b'     => 'ara',
            'code3'       => 'ara',
            'name'        => 'Arabic',
            'native_name' => 'العربية',
        ),
        'an' => array(
            'code'        => 'an',
            'code2_t'     => 'arg',
            'code2_b'     => 'arg',
            'code3'       => 'arg',
            'name'        => 'Aragonese',
            'native_name' => 'aragonés',
        ),
        'hy' => array(
            'code'        => 'hy',
            'code2_t'     => 'hye',
            'code2_b'     => 'arm',
            'code3'       => 'hye',
            'name'        => 'Armenian',
            'native_name' => 'Հայերեն',
        ),
        'as' => array(
            'code'        => 'as',
            'code2_t'     => 'asm',
            'code2_b'     => 'asm',
            'code3'       => 'asm',
            'name'        => 'Assamese',
            'native_name' => 'অসমীয়া',
        ),
        'av' => array(
            'code'        => 'av',
            'code2_t'     => 'ava',
            'code2_b'     => 'ava',
            'code3'       => 'ava',
            'name'        => 'Avaric',
            'native_name' => 'авар мацӀ, магӀарул мацӀ',
        ),
        'ae' => array(
            'code'        => 'ae',
            'code2_t'     => 'ave',
            'code2_b'     => 'ave',
            'code3'       => 'ave',
            'name'        => 'Avestan',
            'native_name' => 'avesta',
        ),
        'ay' => array(
            'code'        => 'ay',
            'code2_t'     => 'aym',
            'code2_b'     => 'aym',
            'code3'       => 'aym',
            'name'        => 'Aymara',
            'native_name' => 'aymar aru',
        ),
        'az' => array(
            'code'        => 'az',
            'code2_t'     => 'aze',
            'code2_b'     => 'aze',
            'code3'       => 'aze',
            'name'        => 'Azerbaijani',
            'native_name' => 'azərbaycan dili',
        ),
        'bm' => array(
            'code'        => 'bm',
            'code2_t'     => 'bam',
            'code2_b'     => 'bam',
            'code3'       => 'bam',
            'name'        => 'Bambara',
            'native_name' => 'bamanankan',
        ),
        'ba' => array(
            'code'        => 'ba',
            'code2_t'     => 'bak',
            'code2_b'     => 'bak',
            'code3'       => 'bak',
            'name'        => 'Bashkir',
            'native_name' => 'башҡорт теле',
        ),
        'eu' => array(
            'code'        => 'eu',
            'code2_t'     => 'eus',
            'code2_b'     => 'baq',
            'code3'       => 'eus',
            'name'        => 'Basque',
            'native_name' => 'euskara, euskera',
        ),
        'be' => array(
            'code'        => 'be',
            'code2_t'     => 'bel',
            'code2_b'     => 'bel',
            'code3'       => 'bel',
            'name'        => 'Belarusian',
            'native_name' => 'беларуская мова',
        ),
        'bn' => array(
            'code'        => 'bn',
            'code2_t'     => 'ben',
            'code2_b'     => 'ben',
            'code3'       => 'ben',
            'name'        => 'Bengali, Bangla',
            'native_name' => 'বাংলা',
        ),
        'bh' => array(
            'code'        => 'bh',
            'code2_t'     => 'bih',
            'code2_b'     => 'bih',
            'code3'       => null,
            'name'        => 'Bihari',
            'native_name' => 'भोजपुरी',
        ),
        'bi' => array(
            'code'        => 'bi',
            'code2_t'     => 'bis',
            'code2_b'     => 'bis',
            'code3'       => 'bis',
            'name'        => 'Bislama',
            'native_name' => 'Bislama',
        ),
        'bs' => array(
            'code'        => 'bs',
            'code2_t'     => 'bos',
            'code2_b'     => 'bos',
            'code3'       => 'bos',
            'name'        => 'Bosnian',
            'native_name' => 'bosanski jezik',
        ),
        'br' => array(
            'code'        => 'br',
            'code2_t'     => 'bre',
            'code2_b'     => 'bre',
            'code3'       => 'bre',
            'name'        => 'Breton',
            'native_name' => 'brezhoneg',
        ),
        'bg' => array(
            'code'        => 'bg',
            'code2_t'     => 'bul',
            'code2_b'     => 'bul',
            'code3'       => 'bul',
            'name'        => 'Bulgarian',
            'native_name' => 'български език',
        ),
        'my' => array(
            'code'        => 'my',
            'code2_t'     => 'mya',
            'code2_b'     => 'bur',
            'code3'       => 'mya',
            'name'        => 'Burmese',
            'native_name' => 'ဗမာစာ',
        ),
        'ca' => array(
            'code'        => 'ca',
            'code2_t'     => 'cat',
            'code2_b'     => 'cat',
            'code3'       => 'cat',
            'name'        => 'Catalan',
            'native_name' => 'català',
        ),
        'ch' => array(
            'code'        => 'ch',
            'code2_t'     => 'cha',
            'code2_b'     => 'cha',
            'code3'       => 'cha',
            'name'        => 'Chamorro',
            'native_name' => 'Chamoru',
        ),
        'ce' => array(
            'code'        => 'ce',
            'code2_t'     => 'che',
            'code2_b'     => 'che',
            'code3'       => 'che',
            'name'        => 'Chechen',
            'native_name' => 'нохчийн мотт',
        ),
        'ny' => array(
            'code'        => 'ny',
            'code2_t'     => 'nya',
            'code2_b'     => 'nya',
            'code3'       => 'nya',
            'name'        => 'Chichewa, Chewa, Nyanja',
            'native_name' => 'chiCheŵa, chinyanja',
        ),
        'zh' => array(
            'code'        => 'zh',
            'code2_t'     => 'zho',
            'code2_b'     => 'chi',
            'code3'       => 'zho',
            'name'        => 'Chinese',
            'native_name' => '中文 (Zhōngwén), 汉语, 漢語',
        ),
        'cv' => array(
            'code'        => 'cv',
            'code2_t'     => 'chv',
            'code2_b'     => 'chv',
            'code3'       => 'chv',
            'name'        => 'Chuvash',
            'native_name' => 'чӑваш чӗлхи',
        ),
        'kw' => array(
            'code'        => 'kw',
            'code2_t'     => 'cor',
            'code2_b'     => 'cor',
            'code3'       => 'cor',
            'name'        => 'Cornish',
            'native_name' => 'Kernewek',
        ),
        'co' => array(
            'code'        => 'co',
            'code2_t'     => 'cos',
            'code2_b'     => 'cos',
            'code3'       => 'cos',
            'name'        => 'Corsican',
            'native_name' => 'corsu, lingua corsa',
        ),
        'cr' => array(
            'code'        => 'cr',
            'code2_t'     => 'cre',
            'code2_b'     => 'cre',
            'code3'       => 'cre',
            'name'        => 'Cree',
            'native_name' => 'ᓀᐦᐃᔭᐍᐏᐣ',
        ),
        'hr' => array(
            'code'        => 'hr',
            'code2_t'     => 'hrv',
            'code2_b'     => 'hrv',
            'code3'       => 'hrv',
            'name'        => 'Croatian',
            'native_name' => 'hrvatski jezik',
        ),
        'cs' => array(
            'code'        => 'cs',
            'code2_t'     => 'ces',
            'code2_b'     => 'cze',
            'code3'       => 'ces',
            'name'        => 'Czech',
            'native_name' => 'čeština, český jazyk',
        ),
        'da' => array(
            'code'        => 'da',
            'code2_t'     => 'dan',
            'code2_b'     => 'dan',
            'code3'       => 'dan',
            'name'        => 'Danish',
            'native_name' => 'dansk',
        ),
        'dv' => array(
            'code'        => 'dv',
            'code2_t'     => 'div',
            'code2_b'     => 'div',
            'code3'       => 'div',
            'name'        => 'Divehi, Dhivehi, Maldivian',
            'native_name' => 'ދިވެހި',
        ),
        'nl' => array(
            'code'        => 'nl',
            'code2_t'     => 'nld',
            'code2_b'     => 'dut',
            'code3'       => 'nld',
            'name'        => 'Dutch',
            'native_name' => 'Nederlands, Vlaams',
        ),
        'dz' => array(
            'code'        => 'dz',
            'code2_t'     => 'dzo',
            'code2_b'     => 'dzo',
            'code3'       => 'dzo',
            'name'        => 'Dzongkha',
            'native_name' => 'རྫོང་ཁ',
        ),
        'en' => array(
            'code'        => 'en',
            'code2_t'     => 'eng',
            'code2_b'     => 'eng',
            'code3'       => 'eng',
            'name'        => 'English',
            'native_name' => 'English',
        ),
        'eo' => array(
            'code'        => 'eo',
            'code2_t'     => 'epo',
            'code2_b'     => 'epo',
            'code3'       => 'epo',
            'name'        => 'Esperanto',
            'native_name' => 'Esperanto',
        ),
        'et' => array(
            'code'        => 'et',
            'code2_t'     => 'est',
            'code2_b'     => 'est',
            'code3'       => 'est',
            'name'        => 'Estonian',
            'native_name' => 'eesti, eesti keel',
        ),
        'ee' => array(
            'code'        => 'ee',
            'code2_t'     => 'ewe',
            'code2_b'     => 'ewe',
            'code3'       => 'ewe',
            'name'        => 'Ewe',
            'native_name' => 'Eʋegbe',
        ),
        'fo' => array(
            'code'        => 'fo',
            'code2_t'     => 'fao',
            'code2_b'     => 'fao',
            'code3'       => 'fao',
            'name'        => 'Faroese',
            'native_name' => 'føroyskt',
        ),
        'fj' => array(
            'code'        => 'fj',
            'code2_t'     => 'fij',
            'code2_b'     => 'fij',
            'code3'       => 'fij',
            'name'        => 'Fijian',
            'native_name' => 'vosa Vakaviti',
        ),
        'fi' => array(
            'code'        => 'fi',
            'code2_t'     => 'fin',
            'code2_b'     => 'fin',
            'code3'       => 'fin',
            'name'        => 'Finnish',
            'native_name' => 'suomi, suomen kieli',
        ),
        'fr' => array(
            'code'        => 'fr',
            'code2_t'     => 'fra',
            'code2_b'     => 'fre',
            'code3'       => 'fra',
            'name'        => 'French',
            'native_name' => 'français, langue française',
        ),
        'ff' => array(
            'code'        => 'ff',
            'code2_t'     => 'ful',
            'code2_b'     => 'ful',
            'code3'       => 'ful',
            'name'        => 'Fula, Fulah, Pulaar, Pular',
            'native_name' => 'Fulfulde, Pulaar, Pular',
        ),
        'gl' => array(
            'code'        => 'gl',
            'code2_t'     => 'glg',
            'code2_b'     => 'glg',
            'code3'       => 'glg',
            'name'        => 'Galician',
            'native_name' => 'galego',
        ),
        'ka' => array(
            'code'        => 'ka',
            'code2_t'     => 'kat',
            'code2_b'     => 'geo',
            'code3'       => 'kat',
            'name'        => 'Georgian',
            'native_name' => 'ქართული',
        ),
        'de' => array(
            'code'        => 'de',
            'code2_t'     => 'deu',
            'code2_b'     => 'ger',
            'code3'       => 'deu',
            'name'        => 'German',
            'native_name' => 'Deutsch',
        ),
        'el' => array(
            'code'        => 'el',
            'code2_t'     => 'ell',
            'code2_b'     => 'gre',
            'code3'       => 'ell',
            'name'        => 'Greek (modern)',
            'native_name' => 'ελληνικά',
        ),
        'gn' => array(
            'code'        => 'gn',
            'code2_t'     => 'grn',
            'code2_b'     => 'grn',
            'code3'       => 'grn',
            'name'        => 'Guaraní',
            'native_name' => 'Avañe\'ẽ',
        ),
        'gu' => array(
            'code'        => 'gu',
            'code2_t'     => 'guj',
            'code2_b'     => 'guj',
            'code3'       => 'guj',
            'name'        => 'Gujarati',
            'native_name' => 'ગુજરાતી',
        ),
        'ht' => array(
            'code'        => 'ht',
            'code2_t'     => 'hat',
            'code2_b'     => 'hat',
            'code3'       => 'hat',
            'name'        => 'Haitian, Haitian Creole',
            'native_name' => 'Kreyòl ayisyen',
        ),
        'ha' => array(
            'code'        => 'ha',
            'code2_t'     => 'hau',
            'code2_b'     => 'hau',
            'code3'       => 'hau',
            'name'        => 'Hausa',
            'native_name' => '(Hausa) هَوُسَ',
        ),
        'he' => array(
            'code'        => 'he',
            'code2_t'     => 'heb',
            'code2_b'     => 'heb',
            'code3'       => 'heb',
            'name'        => 'Hebrew (modern)',
            'native_name' => 'עברית',
        ),
        'hz' => array(
            'code'        => 'hz',
            'code2_t'     => 'her',
            'code2_b'     => 'her',
            'code3'       => 'her',
            'name'        => 'Herero',
            'native_name' => 'Otjiherero',
        ),
        'hi' => array(
            'code'        => 'hi',
            'code2_t'     => 'hin',
            'code2_b'     => 'hin',
            'code3'       => 'hin',
            'name'        => 'Hindi',
            'native_name' => 'हिन्दी, हिंदी',
        ),
        'ho' => array(
            'code'        => 'ho',
            'code2_t'     => 'hmo',
            'code2_b'     => 'hmo',
            'code3'       => 'hmo',
            'name'        => 'Hiri Motu',
            'native_name' => 'Hiri Motu',
        ),
        'hu' => array(
            'code'        => 'hu',
            'code2_t'     => 'hun',
            'code2_b'     => 'hun',
            'code3'       => 'hun',
            'name'        => 'Hungarian',
            'native_name' => 'magyar',
        ),
        'ia' => array(
            'code'        => 'ia',
            'code2_t'     => 'ina',
            'code2_b'     => 'ina',
            'code3'       => 'ina',
            'name'        => 'Interlingua',
            'native_name' => 'Interlingua',
        ),
        'id' => array(
            'code'        => 'id',
            'code2_t'     => 'ind',
            'code2_b'     => 'ind',
            'code3'       => 'ind',
            'name'        => 'Indonesian',
            'native_name' => 'Bahasa Indonesia',
        ),
        'ie' => array(
            'code'        => 'ie',
            'code2_t'     => 'ile',
            'code2_b'     => 'ile',
            'code3'       => 'ile',
            'name'        => 'Interlingue',
            'native_name' => 'Originally called Occidental; then Interlingue after WWII',
        ),
        'ga' => array(
            'code'        => 'ga',
            'code2_t'     => 'gle',
            'code2_b'     => 'gle',
            'code3'       => 'gle',
            'name'        => 'Irish',
            'native_name' => 'Gaeilge',
        ),
        'ig' => array(
            'code'        => 'ig',
            'code2_t'     => 'ibo',
            'code2_b'     => 'ibo',
            'code3'       => 'ibo',
            'name'        => 'Igbo',
            'native_name' => 'Asụsụ Igbo',
        ),
        'ik' => array(
            'code'        => 'ik',
            'code2_t'     => 'ipk',
            'code2_b'     => 'ipk',
            'code3'       => 'ipk',
            'name'        => 'Inupiaq',
            'native_name' => 'Iñupiaq, Iñupiatun',
        ),
        'io' => array(
            'code'        => 'io',
            'code2_t'     => 'ido',
            'code2_b'     => 'ido',
            'code3'       => 'ido',
            'name'        => 'Ido',
            'native_name' => 'Ido',
        ),
        'is' => array(
            'code'        => 'is',
            'code2_t'     => 'isl',
            'code2_b'     => 'ice',
            'code3'       => 'isl',
            'name'        => 'Icelandic',
            'native_name' => 'Íslenska',
        ),
        'it' => array(
            'code'        => 'it',
            'code2_t'     => 'ita',
            'code2_b'     => 'ita',
            'code3'       => 'ita',
            'name'        => 'Italian',
            'native_name' => 'italiano',
        ),
        'iu' => array(
            'code'        => 'iu',
            'code2_t'     => 'iku',
            'code2_b'     => 'iku',
            'code3'       => 'iku',
            'name'        => 'Inuktitut',
            'native_name' => 'ᐃᓄᒃᑎᑐᑦ',
        ),
        'ja' => array(
            'code'        => 'ja',
            'code2_t'     => 'jpn',
            'code2_b'     => 'jpn',
            'code3'       => 'jpn',
            'name'        => 'Japanese',
            'native_name' => '日本語 (にほんご)',
        ),
        'jv' => array(
            'code'        => 'jv',
            'code2_t'     => 'jav',
            'code2_b'     => 'jav',
            'code3'       => 'jav',
            'name'        => 'Javanese',
            'native_name' => 'basa Jawa',
        ),
        'kl' => array(
            'code'        => 'kl',
            'code2_t'     => 'kal',
            'code2_b'     => 'kal',
            'code3'       => 'kal',
            'name'        => 'Kalaallisut, Greenlandic',
            'native_name' => 'kalaallisut, kalaallit oqaasii',
        ),
        'kn' => array(
            'code'        => 'kn',
            'code2_t'     => 'kan',
            'code2_b'     => 'kan',
            'code3'       => 'kan',
            'name'        => 'Kannada',
            'native_name' => 'ಕನ್ನಡ',
        ),
        'kr' => array(
            'code'        => 'kr',
            'code2_t'     => 'kau',
            'code2_b'     => 'kau',
            'code3'       => 'kau',
            'name'        => 'Kanuri',
            'native_name' => 'Kanuri',
        ),
        'ks' => array(
            'code'        => 'ks',
            'code2_t'     => 'kas',
            'code2_b'     => 'kas',
            'code3'       => 'kas',
            'name'        => 'Kashmiri',
            'native_name' => 'कश्मीरी, كشميري‎',
        ),
        'kk' => array(
            'code'        => 'kk',
            'code2_t'     => 'kaz',
            'code2_b'     => 'kaz',
            'code3'       => 'kaz',
            'name'        => 'Kazakh',
            'native_name' => 'қазақ тілі',
        ),
        'km' => array(
            'code'        => 'km',
            'code2_t'     => 'khm',
            'code2_b'     => 'khm',
            'code3'       => 'khm',
            'name'        => 'Khmer',
            'native_name' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
        ),
        'ki' => array(
            'code'        => 'ki',
            'code2_t'     => 'kik',
            'code2_b'     => 'kik',
            'code3'       => 'kik',
            'name'        => 'Kikuyu, Gikuyu',
            'native_name' => 'Gĩkũyũ',
        ),
        'rw' => array(
            'code'        => 'rw',
            'code2_t'     => 'kin',
            'code2_b'     => 'kin',
            'code3'       => 'kin',
            'name'        => 'Kinyarwanda',
            'native_name' => 'Ikinyarwanda',
        ),
        'ky' => array(
            'code'        => 'ky',
            'code2_t'     => 'kir',
            'code2_b'     => 'kir',
            'code3'       => 'kir',
            'name'        => 'Kyrgyz',
            'native_name' => 'Кыргызча, Кыргыз тили',
        ),
        'kv' => array(
            'code'        => 'kv',
            'code2_t'     => 'kom',
            'code2_b'     => 'kom',
            'code3'       => 'kom',
            'name'        => 'Komi',
            'native_name' => 'коми кыв',
        ),
        'kg' => array(
            'code'        => 'kg',
            'code2_t'     => 'kon',
            'code2_b'     => 'kon',
            'code3'       => 'kon',
            'name'        => 'Kongo',
            'native_name' => 'Kikongo',
        ),
        'ko' => array(
            'code'        => 'ko',
            'code2_t'     => 'kor',
            'code2_b'     => 'kor',
            'code3'       => 'kor',
            'name'        => 'Korean',
            'native_name' => '한국어, 조선어',
        ),
        'ku' => array(
            'code'        => 'ku',
            'code2_t'     => 'kur',
            'code2_b'     => 'kur',
            'code3'       => 'kur',
            'name'        => 'Kurdish',
            'native_name' => 'Kurdî, كوردی‎',
        ),
        'kj' => array(
            'code'        => 'kj',
            'code2_t'     => 'kua',
            'code2_b'     => 'kua',
            'code3'       => 'kua',
            'name'        => 'Kwanyama, Kuanyama',
            'native_name' => 'Kuanyama',
        ),
        'la' => array(
            'code'        => 'la',
            'code2_t'     => 'lat',
            'code2_b'     => 'lat',
            'code3'       => 'lat',
            'name'        => 'Latin',
            'native_name' => 'latine, lingua latina',
        ),
        'lb' => array(
            'code'        => 'lb',
            'code2_t'     => 'ltz',
            'code2_b'     => 'ltz',
            'code3'       => 'ltz',
            'name'        => 'Luxembourgish, Letzeburgesch',
            'native_name' => 'Lëtzebuergesch',
        ),
        'lg' => array(
            'code'        => 'lg',
            'code2_t'     => 'lug',
            'code2_b'     => 'lug',
            'code3'       => 'lug',
            'name'        => 'Ganda',
            'native_name' => 'Luganda',
        ),
        'li' => array(
            'code'        => 'li',
            'code2_t'     => 'lim',
            'code2_b'     => 'lim',
            'code3'       => 'lim',
            'name'        => 'Limburgish, Limburgan, Limburger',
            'native_name' => 'Limburgs',
        ),
        'ln' => array(
            'code'        => 'ln',
            'code2_t'     => 'lin',
            'code2_b'     => 'lin',
            'code3'       => 'lin',
            'name'        => 'Lingala',
            'native_name' => 'Lingála',
        ),
        'lo' => array(
            'code'        => 'lo',
            'code2_t'     => 'lao',
            'code2_b'     => 'lao',
            'code3'       => 'lao',
            'name'        => 'Lao',
            'native_name' => 'ພາສາລາວ',
        ),
        'lt' => array(
            'code'        => 'lt',
            'code2_t'     => 'lit',
            'code2_b'     => 'lit',
            'code3'       => 'lit',
            'name'        => 'Lithuanian',
            'native_name' => 'lietuvių kalba',
        ),
        'lu' => array(
            'code'        => 'lu',
            'code2_t'     => 'lub',
            'code2_b'     => 'lub',
            'code3'       => 'lub',
            'name'        => 'Luba-Katanga',
            'native_name' => 'Tshiluba',
        ),
        'lv' => array(
            'code'        => 'lv',
            'code2_t'     => 'lav',
            'code2_b'     => 'lav',
            'code3'       => 'lav',
            'name'        => 'Latvian',
            'native_name' => 'latviešu valoda',
        ),
        'gv' => array(
            'code'        => 'gv',
            'code2_t'     => 'glv',
            'code2_b'     => 'glv',
            'code3'       => 'glv',
            'name'        => 'Manx',
            'native_name' => 'Gaelg, Gailck',
        ),
        'mk' => array(
            'code'        => 'mk',
            'code2_t'     => 'mkd',
            'code2_b'     => 'mac',
            'code3'       => 'mkd',
            'name'        => 'Macedonian',
            'native_name' => 'македонски јазик',
        ),
        'mg' => array(
            'code'        => 'mg',
            'code2_t'     => 'mlg',
            'code2_b'     => 'mlg',
            'code3'       => 'mlg',
            'name'        => 'Malagasy',
            'native_name' => 'fiteny malagasy',
        ),
        'ms' => array(
            'code'        => 'ms',
            'code2_t'     => 'msa',
            'code2_b'     => 'may',
            'code3'       => 'msa',
            'name'        => 'Malay',
            'native_name' => 'bahasa Melayu, بهاس ملايو‎',
        ),
        'ml' => array(
            'code'        => 'ml',
            'code2_t'     => 'mal',
            'code2_b'     => 'mal',
            'code3'       => 'mal',
            'name'        => 'Malayalam',
            'native_name' => 'മലയാളം',
        ),
        'mt' => array(
            'code'        => 'mt',
            'code2_t'     => 'mlt',
            'code2_b'     => 'mlt',
            'code3'       => 'mlt',
            'name'        => 'Maltese',
            'native_name' => 'Malti',
        ),
        'mi' => array(
            'code'        => 'mi',
            'code2_t'     => 'mri',
            'code2_b'     => 'mao',
            'code3'       => 'mri',
            'name'        => 'Māori',
            'native_name' => 'te reo Māori',
        ),
        'mr' => array(
            'code'        => 'mr',
            'code2_t'     => 'mar',
            'code2_b'     => 'mar',
            'code3'       => 'mar',
            'name'        => 'Marathi (Marāṭhī)',
            'native_name' => 'मराठी',
        ),
        'mh' => array(
            'code'        => 'mh',
            'code2_t'     => 'mah',
            'code2_b'     => 'mah',
            'code3'       => 'mah',
            'name'        => 'Marshallese',
            'native_name' => 'Kajin M̧ajeļ',
        ),
        'mn' => array(
            'code'        => 'mn',
            'code2_t'     => 'mon',
            'code2_b'     => 'mon',
            'code3'       => 'mon',
            'name'        => 'Mongolian',
            'native_name' => 'монгол',
        ),
        'na' => array(
            'code'        => 'na',
            'code2_t'     => 'nau',
            'code2_b'     => 'nau',
            'code3'       => 'nau',
            'name'        => 'Nauru',
            'native_name' => 'Ekakairũ Naoero',
        ),
        'nv' => array(
            'code'        => 'nv',
            'code2_t'     => 'nav',
            'code2_b'     => 'nav',
            'code3'       => 'nav',
            'name'        => 'Navajo, Navaho',
            'native_name' => 'Diné bizaad',
        ),
        'nd' => array(
            'code'        => 'nd',
            'code2_t'     => 'nde',
            'code2_b'     => 'nde',
            'code3'       => 'nde',
            'name'        => 'Northern Ndebele',
            'native_name' => 'isiNdebele',
        ),
        'ne' => array(
            'code'        => 'ne',
            'code2_t'     => 'nep',
            'code2_b'     => 'nep',
            'code3'       => 'nep',
            'name'        => 'Nepali',
            'native_name' => 'नेपाली',
        ),
        'ng' => array(
            'code'        => 'ng',
            'code2_t'     => 'ndo',
            'code2_b'     => 'ndo',
            'code3'       => 'ndo',
            'name'        => 'Ndonga',
            'native_name' => 'Owambo',
        ),
        'nb' => array(
            'code'        => 'nb',
            'code2_t'     => 'nob',
            'code2_b'     => 'nob',
            'code3'       => 'nob',
            'name'        => 'Norwegian Bokmål',
            'native_name' => 'Norsk bokmål',
        ),
        'nn' => array(
            'code'        => 'nn',
            'code2_t'     => 'nno',
            'code2_b'     => 'nno',
            'code3'       => 'nno',
            'name'        => 'Norwegian Nynorsk',
            'native_name' => 'Norsk nynorsk',
        ),
        'no' => array(
            'code'        => 'no',
            'code2_t'     => 'nor',
            'code2_b'     => 'nor',
            'code3'       => 'nor',
            'name'        => 'Norwegian',
            'native_name' => 'Norsk',
        ),
        'ii' => array(
            'code'        => 'ii',
            'code2_t'     => 'iii',
            'code2_b'     => 'iii',
            'code3'       => 'iii',
            'name'        => 'Nuosu',
            'native_name' => 'ꆈꌠ꒿ Nuosuhxop',
        ),
        'nr' => array(
            'code'        => 'nr',
            'code2_t'     => 'nbl',
            'code2_b'     => 'nbl',
            'code3'       => 'nbl',
            'name'        => 'Southern Ndebele',
            'native_name' => 'isiNdebele',
        ),
        'oc' => array(
            'code'        => 'oc',
            'code2_t'     => 'oci',
            'code2_b'     => 'oci',
            'code3'       => 'oci',
            'name'        => 'Occitan',
            'native_name' => 'occitan, lenga d\'òc',
        ),
        'oj' => array(
            'code'        => 'oj',
            'code2_t'     => 'oji',
            'code2_b'     => 'oji',
            'code3'       => 'oji',
            'name'        => 'Ojibwe, Ojibwa',
            'native_name' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
        ),
        'cu' => array(
            'code'        => 'cu',
            'code2_t'     => 'chu',
            'code2_b'     => 'chu',
            'code3'       => 'chu',
            'name'        => 'Old Church Slavonic, Church Slavonic, Old Bulgarian',
            'native_name' => 'ѩзыкъ словѣньскъ',
        ),
        'om' => array(
            'code'        => 'om',
            'code2_t'     => 'orm',
            'code2_b'     => 'orm',
            'code3'       => 'orm',
            'name'        => 'Oromo',
            'native_name' => 'Afaan Oromoo',
        ),
        'or' => array(
            'code'        => 'or',
            'code2_t'     => 'ori',
            'code2_b'     => 'ori',
            'code3'       => 'ori',
            'name'        => 'Oriya',
            'native_name' => 'ଓଡ଼ିଆ',
        ),
        'os' => array(
            'code'        => 'os',
            'code2_t'     => 'oss',
            'code2_b'     => 'oss',
            'code3'       => 'oss',
            'name'        => 'Ossetian, Ossetic',
            'native_name' => 'ирон æвзаг',
        ),
        'pa' => array(
            'code'        => 'pa',
            'code2_t'     => 'pan',
            'code2_b'     => 'pan',
            'code3'       => 'pan',
            'name'        => 'Panjabi, Punjabi',
            'native_name' => 'ਪੰਜਾਬੀ, پنجابی‎',
        ),
        'pi' => array(
            'code'        => 'pi',
            'code2_t'     => 'pli',
            'code2_b'     => 'pli',
            'code3'       => 'pli',
            'name'        => 'Pāli',
            'native_name' => 'पाऴि',
        ),
        'fa' => array(
            'code'        => 'fa',
            'code2_t'     => 'fas',
            'code2_b'     => 'per',
            'code3'       => 'fas',
            'name'        => 'Persian (Farsi)',
            'native_name' => 'فارسی',
        ),
        'pl' => array(
            'code'        => 'pl',
            'code2_t'     => 'pol',
            'code2_b'     => 'pol',
            'code3'       => 'pol',
            'name'        => 'Polish',
            'native_name' => 'język polski, polszczyzna',
        ),
        'ps' => array(
            'code'        => 'ps',
            'code2_t'     => 'pus',
            'code2_b'     => 'pus',
            'code3'       => 'pus',
            'name'        => 'Pashto, Pushto',
            'native_name' => 'پښتو',
        ),
        'pt' => array(
            'code'        => 'pt',
            'code2_t'     => 'por',
            'code2_b'     => 'por',
            'code3'       => 'por',
            'name'        => 'Portuguese',
            'native_name' => 'português',
        ),
        'qu' => array(
            'code'        => 'qu',
            'code2_t'     => 'que',
            'code2_b'     => 'que',
            'code3'       => 'que',
            'name'        => 'Quechua',
            'native_name' => 'Runa Simi, Kichwa',
        ),
        'rm' => array(
            'code'        => 'rm',
            'code2_t'     => 'roh',
            'code2_b'     => 'roh',
            'code3'       => 'roh',
            'name'        => 'Romansh',
            'native_name' => 'rumantsch grischun',
        ),
        'rn' => array(
            'code'        => 'rn',
            'code2_t'     => 'run',
            'code2_b'     => 'run',
            'code3'       => 'run',
            'name'        => 'Kirundi',
            'native_name' => 'Ikirundi',
        ),
        'ro' => array(
            'code'        => 'ro',
            'code2_t'     => 'ron',
            'code2_b'     => 'rum',
            'code3'       => 'ron',
            'name'        => 'Romanian',
            'native_name' => 'limba română',
        ),
        'ru' => array(
            'code'        => 'ru',
            'code2_t'     => 'rus',
            'code2_b'     => 'rus',
            'code3'       => 'rus',
            'name'        => 'Russian',
            'native_name' => 'Русский',
        ),
        'sa' => array(
            'code'        => 'sa',
            'code2_t'     => 'san',
            'code2_b'     => 'san',
            'code3'       => 'san',
            'name'        => 'Sanskrit (Saṁskṛta)',
            'native_name' => 'संस्कृतम्',
        ),
        'sc' => array(
            'code'        => 'sc',
            'code2_t'     => 'srd',
            'code2_b'     => 'srd',
            'code3'       => 'srd',
            'name'        => 'Sardinian',
            'native_name' => 'sardu',
        ),
        'sd' => array(
            'code'        => 'sd',
            'code2_t'     => 'snd',
            'code2_b'     => 'snd',
            'code3'       => 'snd',
            'name'        => 'Sindhi',
            'native_name' => 'सिन्धी, سنڌي، سندھی‎',
        ),
        'se' => array(
            'code'        => 'se',
            'code2_t'     => 'sme',
            'code2_b'     => 'sme',
            'code3'       => 'sme',
            'name'        => 'Northern Sami',
            'native_name' => 'Davvisámegiella',
        ),
        'sm' => array(
            'code'        => 'sm',
            'code2_t'     => 'smo',
            'code2_b'     => 'smo',
            'code3'       => 'smo',
            'name'        => 'Samoan',
            'native_name' => 'gagana fa\'a Samoa',
        ),
        'sg' => array(
            'code'        => 'sg',
            'code2_t'     => 'sag',
            'code2_b'     => 'sag',
            'code3'       => 'sag',
            'name'        => 'Sango',
            'native_name' => 'yângâ tî sängö',
        ),
        'sr' => array(
            'code'        => 'sr',
            'code2_t'     => 'srp',
            'code2_b'     => 'srp',
            'code3'       => 'srp',
            'name'        => 'Serbian',
            'native_name' => 'српски језик',
        ),
        'gd' => array(
            'code'        => 'gd',
            'code2_t'     => 'gla',
            'code2_b'     => 'gla',
            'code3'       => 'gla',
            'name'        => 'Scottish Gaelic, Gaelic',
            'native_name' => 'Gàidhlig',
        ),
        'sn' => array(
            'code'        => 'sn',
            'code2_t'     => 'sna',
            'code2_b'     => 'sna',
            'code3'       => 'sna',
            'name'        => 'Shona',
            'native_name' => 'chiShona',
        ),
        'si' => array(
            'code'        => 'si',
            'code2_t'     => 'sin',
            'code2_b'     => 'sin',
            'code3'       => 'sin',
            'name'        => 'Sinhala, Sinhalese',
            'native_name' => 'සිංහල',
        ),
        'sk' => array(
            'code'        => 'sk',
            'code2_t'     => 'slk',
            'code2_b'     => 'slo',
            'code3'       => 'slk',
            'name'        => 'Slovak',
            'native_name' => 'slovenčina, slovenský jazyk',
        ),
        'sl' => array(
            'code'        => 'sl',
            'code2_t'     => 'slv',
            'code2_b'     => 'slv',
            'code3'       => 'slv',
            'name'        => 'Slovene',
            'native_name' => 'slovenski jezik, slovenščina',
        ),
        'so' => array(
            'code'        => 'so',
            'code2_t'     => 'som',
            'code2_b'     => 'som',
            'code3'       => 'som',
            'name'        => 'Somali',
            'native_name' => 'Soomaaliga, af Soomaali',
        ),
        'st' => array(
            'code'        => 'st',
            'code2_t'     => 'sot',
            'code2_b'     => 'sot',
            'code3'       => 'sot',
            'name'        => 'Southern Sotho',
            'native_name' => 'Sesotho',
        ),
        'es' => array(
            'code'        => 'es',
            'code2_t'     => 'spa',
            'code2_b'     => 'spa',
            'code3'       => 'spa',
            'name'        => 'Spanish',
            'native_name' => 'español',
        ),
        'su' => array(
            'code'        => 'su',
            'code2_t'     => 'sun',
            'code2_b'     => 'sun',
            'code3'       => 'sun',
            'name'        => 'Sundanese',
            'native_name' => 'Basa Sunda',
        ),
        'sw' => array(
            'code'        => 'sw',
            'code2_t'     => 'swa',
            'code2_b'     => 'swa',
            'code3'       => 'swa',
            'name'        => 'Swahili',
            'native_name' => 'Kiswahili',
        ),
        'ss' => array(
            'code'        => 'ss',
            'code2_t'     => 'ssw',
            'code2_b'     => 'ssw',
            'code3'       => 'ssw',
            'name'        => 'Swati',
            'native_name' => 'SiSwati',
        ),
        'sv' => array(
            'code'        => 'sv',
            'code2_t'     => 'swe',
            'code2_b'     => 'swe',
            'code3'       => 'swe',
            'name'        => 'Swedish',
            'native_name' => 'svenska',
        ),
        'ta' => array(
            'code'        => 'ta',
            'code2_t'     => 'tam',
            'code2_b'     => 'tam',
            'code3'       => 'tam',
            'name'        => 'Tamil',
            'native_name' => 'தமிழ்',
        ),
        'te' => array(
            'code'        => 'te',
            'code2_t'     => 'tel',
            'code2_b'     => 'tel',
            'code3'       => 'tel',
            'name'        => 'Telugu',
            'native_name' => 'తెలుగు',
        ),
        'tg' => array(
            'code'        => 'tg',
            'code2_t'     => 'tgk',
            'code2_b'     => 'tgk',
            'code3'       => 'tgk',
            'name'        => 'Tajik',
            'native_name' => 'тоҷикӣ, toçikī, تاجیکی‎',
        ),
        'th' => array(
            'code'        => 'th',
            'code2_t'     => 'tha',
            'code2_b'     => 'tha',
            'code3'       => 'tha',
            'name'        => 'Thai',
            'native_name' => 'ไทย',
        ),
        'ti' => array(
            'code'        => 'ti',
            'code2_t'     => 'tir',
            'code2_b'     => 'tir',
            'code3'       => 'tir',
            'name'        => 'Tigrinya',
            'native_name' => 'ትግርኛ',
        ),
        'bo' => array(
            'code'        => 'bo',
            'code2_t'     => 'bod',
            'code2_b'     => 'tib',
            'code3'       => 'bod',
            'name'        => 'Tibetan Standard, Tibetan, Central',
            'native_name' => 'བོད་ཡིག',
        ),
        'tk' => array(
            'code'        => 'tk',
            'code2_t'     => 'tuk',
            'code2_b'     => 'tuk',
            'code3'       => 'tuk',
            'name'        => 'Turkmen',
            'native_name' => 'Türkmen, Түркмен',
        ),
        'tl' => array(
            'code'        => 'tl',
            'code2_t'     => 'tgl',
            'code2_b'     => 'tgl',
            'code3'       => 'tgl',
            'name'        => 'Tagalog',
            'native_name' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
        ),
        'tn' => array(
            'code'        => 'tn',
            'code2_t'     => 'tsn',
            'code2_b'     => 'tsn',
            'code3'       => 'tsn',
            'name'        => 'Tswana',
            'native_name' => 'Setswana',
        ),
        'to' => array(
            'code'        => 'to',
            'code2_t'     => 'ton',
            'code2_b'     => 'ton',
            'code3'       => 'ton',
            'name'        => 'Tonga (Tonga Islands)',
            'native_name' => 'faka Tonga',
        ),
        'tr' => array(
            'code'        => 'tr',
            'code2_t'     => 'tur',
            'code2_b'     => 'tur',
            'code3'       => 'tur',
            'name'        => 'Turkish',
            'native_name' => 'Türkçe',
        ),
        'ts' => array(
            'code'        => 'ts',
            'code2_t'     => 'tso',
            'code2_b'     => 'tso',
            'code3'       => 'tso',
            'name'        => 'Tsonga',
            'native_name' => 'Xitsonga',
        ),
        'tt' => array(
            'code'        => 'tt',
            'code2_t'     => 'tat',
            'code2_b'     => 'tat',
            'code3'       => 'tat',
            'name'        => 'Tatar',
            'native_name' => 'татар теле, tatar tele',
        ),
        'tw' => array(
            'code'        => 'tw',
            'code2_t'     => 'twi',
            'code2_b'     => 'twi',
            'code3'       => 'twi',
            'name'        => 'Twi',
            'native_name' => 'Twi',
        ),
        'ty' => array(
            'code'        => 'ty',
            'code2_t'     => 'tah',
            'code2_b'     => 'tah',
            'code3'       => 'tah',
            'name'        => 'Tahitian',
            'native_name' => 'Reo Tahiti',
        ),
        'ug' => array(
            'code'        => 'ug',
            'code2_t'     => 'uig',
            'code2_b'     => 'uig',
            'code3'       => 'uig',
            'name'        => 'Uyghur',
            'native_name' => 'ئۇيغۇرچە‎, Uyghurche',
        ),
        'uk' => array(
            'code'        => 'uk',
            'code2_t'     => 'ukr',
            'code2_b'     => 'ukr',
            'code3'       => 'ukr',
            'name'        => 'Ukrainian',
            'native_name' => 'українська мова',
        ),
        'ur' => array(
            'code'        => 'ur',
            'code2_t'     => 'urd',
            'code2_b'     => 'urd',
            'code3'       => 'urd',
            'name'        => 'Urdu',
            'native_name' => 'اردو',
        ),
        'uz' => array(
            'code'        => 'uz',
            'code2_t'     => 'uzb',
            'code2_b'     => 'uzb',
            'code3'       => 'uzb',
            'name'        => 'Uzbek',
            'native_name' => 'Oʻzbek, Ўзбек, أۇزبېك‎',
        ),
        've' => array(
            'code'        => 've',
            'code2_t'     => 'ven',
            'code2_b'     => 'ven',
            'code3'       => 'ven',
            'name'        => 'Venda',
            'native_name' => 'Tshivenḓa',
        ),
        'vi' => array(
            'code'        => 'vi',
            'code2_t'     => 'vie',
            'code2_b'     => 'vie',
            'code3'       => 'vie',
            'name'        => 'Vietnamese',
            'native_name' => 'Việt Nam',
        ),
        'vo' => array(
            'code'        => 'vo',
            'code2_t'     => 'vol',
            'code2_b'     => 'vol',
            'code3'       => 'vol',
            'name'        => 'Volapük',
            'native_name' => 'Volapük',
        ),
        'wa' => array(
            'code'        => 'wa',
            'code2_t'     => 'wln',
            'code2_b'     => 'wln',
            'code3'       => 'wln',
            'name'        => 'Walloon',
            'native_name' => 'walon',
        ),
        'cy' => array(
            'code'        => 'cy',
            'code2_t'     => 'cym',
            'code2_b'     => 'wel',
            'code3'       => 'cym',
            'name'        => 'Welsh',
            'native_name' => 'Cymraeg',
        ),
        'wo' => array(
            'code'        => 'wo',
            'code2_t'     => 'wol',
            'code2_b'     => 'wol',
            'code3'       => 'wol',
            'name'        => 'Wolof',
            'native_name' => 'Wollof',
        ),
        'fy' => array(
            'code'        => 'fy',
            'code2_t'     => 'fry',
            'code2_b'     => 'fry',
            'code3'       => 'fry',
            'name'        => 'Western Frisian',
            'native_name' => 'Frysk',
        ),
        'xh' => array(
            'code'        => 'xh',
            'code2_t'     => 'xho',
            'code2_b'     => 'xho',
            'code3'       => 'xho',
            'name'        => 'Xhosa',
            'native_name' => 'isiXhosa',
        ),
        'yi' => array(
            'code'        => 'yi',
            'code2_t'     => 'yid',
            'code2_b'     => 'yid',
            'code3'       => 'yid',
            'name'        => 'Yiddish',
            'native_name' => 'ייִדיש',
        ),
        'yo' => array(
            'code'        => 'yo',
            'code2_t'     => 'yor',
            'code2_b'     => 'yor',
            'code3'       => 'yor',
            'name'        => 'Yoruba',
            'native_name' => 'Yorùbá',
        ),
        'za' => array(
            'code'        => 'za',
            'code2_t'     => 'zha',
            'code2_b'     => 'zha',
            'code3'       => 'zha',
            'name'        => 'Zhuang, Chuang',
            'native_name' => 'Saɯ cueŋƅ, Saw cuengh',
        ),
        'zu' => array(
            'code'        => 'zu',
            'code2_t'     => 'zul',
            'code2_b'     => 'zul',
            'code3'       => 'zul',
            'name'        => 'Zulu',
            'native_name' => 'isiZulu',
        ),
    );

    /**
     * Get language name from ISO-639-1 (two-letters code)
     *
     * @param string $code
     * @return array|null
     */
    public function getByCode($code)
    {
        if (strlen($code) !== 2) {
            return null;
        }

        foreach ($this->languages as $language) {
            if (strcasecmp($code, $language['code']) === 0) {
                return $language;
            }
        }

        return null;
    }

    /**
     * Get language name from ISO-639-2/b (three-letter codes) bibliographic
     *
     * @param string $code
     * @return array|null
     */
    public function getByCode2B($code)
    {
        if (strlen($code) !== 3) {
            return null;
        }

        foreach ($this->languages as $language) {
            if (strcasecmp($code, $language['code2_B']) === 0) {
                return $language;
            }
        }

        return null;
    }

    /**
     * Get language name from ISO-639-2/t (three-letter codes) terminologic
     *
     * @param string $code
     * @return array|null
     */
    public function getByCode2T($code)
    {
        if (strlen($code) !== 3) {
            return null;
        }
        
        foreach ($this->languages as $language) {
            if (strcasecmp($code, $language['code2_T']) === 0) {
                return $language;
            }
        }

        return null;
    }

    /**
     * Get language name from ISO-639-3 (three-letter codes)
     *
     * @param string $code
     * @return array|null
     */
    public function getByCode3($code)
    {
        if (strlen($code) !== 3) {
            return null;
        }

        foreach ($this->languages as $language) {
            if (strcasecmp($code, $language['code3']) === 0) {
                return $language;
            }
        }

        return null;
    }
}